pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master

steps:
- script: |
    git config user.email "gissella.reyesj@alumnos.uv.cl"  
    git config user.name "Gissella Reyes"
    git checkout master
    git add --all
    git push https://$(gitToken)@github.com/igssellar/Ventas.git --force
  displayName: 'Github'
  #fin publicando artifacts

